# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5.2'
# Use Puma as the app server
gem 'puma', '~> 4.1'
#gem 'mimemagic', github: 'mimemagicrb/mimemagic', ref: '01f92d86d15d85cfd0f20dabd025dcbd36a8a60f'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'devise-jwt', '~> 0.8.0'
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

gem 'sidekiq', '~> 6.1', '>= 6.1.2'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '11.1.3', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'simplecov', '~> 0.21.2'
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '2.1.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.1.1'
gem 'sentry-rails', '4.2.1' 
gem 'sentry-ruby', '4.2.1'
gem 'sentry-sidekiq', '4.2.0'

gem 'dotenv', '~> 2.7', '>= 2.7.6'
gem 'jsonapi-resources', '~> 0.10.2'

gem 'redis', '4.2.5'
gem 'redis-namespace', '1.8.0'
gem 'redis-rails', '5.0.2'
gem 'sidekiq-cron', '1.2.0'
gem 'httparty', '0.18.1'
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', '1.2.9', platforms: %i[mingw mswin x64_mingw jruby]

gem 'mimemagic', github: 'mimemagicrb/mimemagic', ref: '01f92d86d15d85cfd0f20dabd025dcbd36a8a60f'

gem 'rubocop', '~> 1.16', require: false

gem 'newrelic_rpm', '~> 7.1'

gem 'audited', '~> 4.9'

gem 'leaderboard', '~> 3.12', '>= 3.12.1'
