name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: devsnest_test
      DB_USER: root
      DB_PASSWORD: root
      CC_TEST_REPORTER_ID: 8f0038687a9ad7675365b6a1ecde37608d55e4fa148d2da81a0653dc1dc6937d

    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e        
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Install Bundler
        working-directory: ./devsnest
        run: bundle install --jobs 4 --retry 3

      - name: Run Migrations
        working-directory: ./devsnest
        run: |
            bundle exec rake db:create
            bundle exec rake db:migtrate

      - name: Run Tests
        working-directory: ./devsnest
        run: bundle exec rspec spec
