name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_NAME: devsnest_test
      MYSQL_USERNAME: root
      MYSQL_PASSWORD:
      CC_TEST_REPORTER_ID: 8f0038687a9ad7675365b6a1ecde37608d55e4fa148d2da81a0653dc1dc6937d

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: devsnest_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e        
        with:
          ruby-version: 2.7.2
          bundler-cache: true


      - name: Run Tests
        env:
          RAILS_ENV: test
          DATABASE_PORT: 3306
        working-directory: ./devsnest
        run: |
            bundle install --jobs 4 --retry 3
            bundle exec rake db:create
            bundle exec rake db:migtrate
            bundle exec rspec spec
